package ir.channel.telegram_news

import android.app.Activity
import android.content.ContentValues
import android.media.MediaScannerConnection
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.util.Base64
import android.webkit.CookieManager
import android.webkit.JavascriptInterface
import android.webkit.URLUtil
import android.webkit.MimeTypeMap
import android.webkit.WebView
import io.flutter.plugin.common.MethodChannel
import org.json.JSONObject
import java.io.FileOutputStream
import java.io.BufferedInputStream
import java.io.ByteArrayInputStream
import java.io.File
import java.io.InputStream
import java.net.HttpURLConnection
import java.net.URL
import java.net.URLConnection
import java.util.UUID
import java.util.concurrent.ConcurrentHashMap

/**
 * A WebView does not download files by itself. Save HTTPS downloads with the
 * site's session cookies, and support blob: links generated by web messengers.
 * Android 10+ MediaStore puts images/videos in the gallery and other files in
 * the public Downloads/Gozar folder, without broad storage permissions.
 */
class GozarSocialDownloads(
    private val activity: Activity,
    private val web: WebView,
    private val index: Int,
    private val events: MethodChannel
) {
    private class BlobTransfer(
        val filename: String, var mimeHint: String, val file: File
    ) {
        val output = FileOutputStream(file)
        var expectedSize = -1L
        var written = 0L
        var started = false
        var closed = false
        @Synchronized fun close() {
            if (!closed) {
                closed = true
                output.close()
            }
        }
        @Synchronized fun abort() {
            close()
            file.delete()
        }
    }

    private val transfers = ConcurrentHashMap<String, BlobTransfer>()
    // Blob data is streamed to a temporary file rather than retained in RAM.
    private val maxBlob = 512L * 1024 * 1024
    private val maxHttps = 512L * 1024 * 1024

    init {
        // No arbitrary URL or file path can be submitted through this bridge.
        // The only accepted token is a random, short-lived one issued after a
        // user-initiated WebView download for this specific page.
        web.addJavascriptInterface(BlobPort(), "GozarFileBridge")
        web.setDownloadListener { url, userAgent, disposition, mime, _ ->
            saveUserDownload(url, userAgent, disposition, mime)
        }
    }

    /** Called from the website download action or the user's Save image dialog. */
    fun saveUserDownload(url: String, userAgent: String?,
                         disposition: String?, mime: String?) {
        try {
            val uri = android.net.Uri.parse(url)
            when (uri.scheme?.lowercase()) {
                "https" -> {
                    notify("downloadStarted")
                    val agent = userAgent ?: web.settings.userAgentString
                    Thread {
                        try {
                            val request = URL(url).openConnection() as HttpURLConnection
                            request.connectTimeout = 20000
                            request.readTimeout = 45000
                            request.instanceFollowRedirects = true
                            request.setRequestProperty("User-Agent", agent)
                            CookieManager.getInstance().getCookie(url)?.let {
                                request.setRequestProperty("Cookie", it)
                            }
                            try {
                                if (request.responseCode !in 200..299 ||
                                    request.url.protocol != "https") {
                                    throw IllegalStateException("HTTPS download failed")
                                }
                                val name = filename(url,
                                    request.getHeaderField("Content-Disposition") ?: disposition,
                                    mime)
                                val kind = request.contentType?.substringBefore(';')?.trim()
                                    ?.takeIf { it.isNotBlank() }
                                    ?: mime ?: "application/octet-stream"
                                request.inputStream.use { input ->
                                    store(input, name, kind, maxHttps)
                                }
                            } finally {
                                request.disconnect()
                            }
                        } catch (_: Exception) {
                            notify("downloadError")
                        }
                    }.start()
                }
                "blob" -> downloadBlob(url, disposition, mime)
                "data" -> saveInlineImage(url)
                else -> notify("downloadError")
            }
        } catch (_: Exception) {
            notify("downloadError")
        }
    }

    // Some web messengers render received images from data: URLs; they are
    // not HTTPS downloads and cannot be fetched as a blob: URL. Decode only
    // a bounded, explicit base64 image after the user's Save action.
    private fun saveInlineImage(url: String) {
        val comma = url.indexOf(',')
        if (comma !in 20..80 || url.length > 12 * 1024 * 1024) {
            notify("downloadError")
            return
        }
        val mime = url.substring(5, comma).lowercase()
        if (mime !in setOf(
            "image/jpeg;base64", "image/png;base64", "image/webp;base64",
            "image/gif;base64"
        )) {
            notify("downloadError")
            return
        }
        notify("downloadStarted")
        Thread {
            try {
                val bytes = Base64.decode(url.substring(comma + 1), Base64.DEFAULT)
                if (bytes.isEmpty() || bytes.size > 8 * 1024 * 1024) {
                    throw IllegalStateException("Inline image too large")
                }
                val type = mime.substringBefore(';')
                val name = filename("https://local.invalid/image", null, type)
                ByteArrayInputStream(bytes).use {
                    store(it, name, type, 8L * 1024 * 1024)
                }
            } catch (_: Exception) {
                notify("downloadError")
            }
        }.start()
    }

    private fun filename(url: String, disposition: String?, mime: String?): String {
        val guessed = URLUtil.guessFileName(url, disposition, mime)
        val sanitized = guessed.substringAfterLast('/').substringAfterLast('\\')
            .replace(Regex("[^\\p{L}\\p{N}._ -]"), "_").take(100)
        return sanitized.ifBlank { "Gozar-download-${System.currentTimeMillis()}" }
    }

    private fun notify(method: String, gallery: Boolean = false) {
        activity.runOnUiThread {
            events.invokeMethod(method, mapOf("index" to index, "gallery" to gallery))
        }
    }

    // Websites often send image downloads as application/octet-stream, or
    // label a PNG as JPEG. Detect common media signatures *without consuming*
    // any bytes, so gallery registration uses the actual file type.
    private fun sniffMime(input: BufferedInputStream, name: String, hint: String): String {
        input.mark(32)
        val bytes = ByteArray(32)
        var count = 0
        try {
            while (count < bytes.size) {
                val read = input.read(bytes, count, bytes.size - count)
                if (read < 0) break
                if (read == 0) break
                count += read
            }
        } finally { input.reset() }
        fun matches(vararg header: Int): Boolean =
            count >= header.size && header.indices.all { i ->
                (bytes[i].toInt() and 0xff) == header[i]
            }
        val brand = if (count >= 12) String(bytes, 8, 4, Charsets.US_ASCII)
            else ""
        val isFtyp = count >= 12 &&
            String(bytes, 4, 4, Charsets.US_ASCII) == "ftyp"
        val signature = when {
            matches(0xff, 0xd8, 0xff) -> "image/jpeg"
            matches(0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a) -> "image/png"
            matches(0x47, 0x49, 0x46, 0x38) -> "image/gif"
            matches(0x52, 0x49, 0x46, 0x46) &&
                count >= 12 && String(bytes, 8, 4, Charsets.US_ASCII) == "WEBP" ->
                "image/webp"
            isFtyp && brand in setOf("avif", "avis") -> "image/avif"
            isFtyp && brand in setOf("heic", "heix", "hevc", "hevx", "mif1") ->
                "image/heic"
            isFtyp && brand in setOf(
                "isom", "iso2", "avc1", "mp41", "mp42", "M4V ", "qt  "
            ) -> "video/mp4"
            matches(0x1a, 0x45, 0xdf, 0xa3) -> "video/webm"
            matches(0x25, 0x50, 0x44, 0x46, 0x2d) -> "application/pdf"
            else -> null
        }
        if (signature != null) return signature
        val declared = hint.substringBefore(';').trim().lowercase()
        val inferred = URLConnection.guessContentTypeFromName(name)
        return when {
            declared.isBlank() || declared == "application/octet-stream" ->
                inferred ?: "application/octet-stream"
            declared == "text/plain" && inferred != null -> inferred
            else -> declared
        }
    }

    private fun store(input: InputStream, name: String, mimeHint: String, limit: Long) {
        val buffered = BufferedInputStream(input)
        val mime = sniffMime(buffered, name, mimeHint)
        val gallery = mime.startsWith("image/") || mime.startsWith("video/")
        val inferred = when (mime) {
            "image/jpeg" -> "jpg"
            "image/png" -> "png"
            "image/gif" -> "gif"
            "image/webp" -> "webp"
            "image/avif" -> "avif"
            "image/heic" -> "heic"
            "video/mp4" -> "mp4"
            "video/webm" -> "webm"
            "application/pdf" -> "pdf"
            "application/vnd.android.package-archive" -> "apk"
            else -> MimeTypeMap.getSingleton().getExtensionFromMimeType(mime)
        }
        val ext = name.substringAfterLast('.', "").lowercase()
        val validExtension = ext.length in 2..6 &&
            ext.all { it.isLetterOrDigit() } &&
            // URLUtil may call an unknown blob 'download.bin', even when
            // the content is a PNG or a video.
            ext !in setOf("bin", "dat", "tmp") &&
            (!gallery || inferred.isNullOrBlank() ||
                ext == inferred || (mime == "image/jpeg" && ext == "jpeg"))
        val baseName = if (ext in setOf("bin", "dat", "tmp") ||
            (gallery && !validExtension && name.contains('.'))) {
            name.substringBeforeLast('.')
        } else name
        val displayName = if (!inferred.isNullOrBlank() && !validExtension) {
            "$baseName.$inferred"
        } else name
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            val collection = when {
                mime.startsWith("image/") -> MediaStore.Images.Media.EXTERNAL_CONTENT_URI
                mime.startsWith("video/") -> MediaStore.Video.Media.EXTERNAL_CONTENT_URI
                else -> MediaStore.Downloads.EXTERNAL_CONTENT_URI
            }
            val folder = when {
                mime.startsWith("image/") -> Environment.DIRECTORY_PICTURES
                mime.startsWith("video/") -> Environment.DIRECTORY_MOVIES
                else -> Environment.DIRECTORY_DOWNLOADS
            }
            val values = ContentValues().apply {
                put(MediaStore.MediaColumns.DISPLAY_NAME, displayName)
                put(MediaStore.MediaColumns.MIME_TYPE, mime)
                put(MediaStore.MediaColumns.RELATIVE_PATH, "$folder/Gozar")
                put(MediaStore.MediaColumns.IS_PENDING, 1)
            }
            val uri = activity.contentResolver.insert(collection, values)
                ?: throw IllegalStateException("MediaStore unavailable")
            try {
                activity.contentResolver.openOutputStream(uri)?.use { output ->
                    val buffer = ByteArray(65536)
                    var written = 0L
                    while (true) {
                        val count = buffered.read(buffer)
                        if (count < 0) break
                        written += count
                        if (written > limit) throw IllegalStateException("File too large")
                        output.write(buffer, 0, count)
                    }
                    if (written == 0L) throw IllegalStateException("Empty download")
                } ?: throw IllegalStateException("Cannot open MediaStore output")
                activity.contentResolver.update(uri, ContentValues().apply {
                    put(MediaStore.MediaColumns.IS_PENDING, 0)
                }, null, null)
                notify("downloadSaved", gallery)
            } catch (error: Exception) {
                activity.contentResolver.delete(uri, null, null)
                throw error
            }
        } else {
            // Gozar's supported A54 is Android 10+, but avoid crashing on older devices.
            val directory = activity.getExternalFilesDir(
                if (gallery) Environment.DIRECTORY_PICTURES else Environment.DIRECTORY_DOWNLOADS
            ) ?: throw IllegalStateException("Storage unavailable")
            directory.mkdirs()
            val output = File(directory, displayName)
            output.outputStream().use { dest -> buffered.copyTo(dest) }
            if (gallery) MediaScannerConnection.scanFile(
                activity, arrayOf(output.absolutePath), arrayOf(mime), null
            )
            notify("downloadSaved", gallery)
        }
    }

    private fun downloadBlob(url: String, disposition: String?, mime: String?) {
        val token = UUID.randomUUID().toString()
        if (transfers.size >= 2) {
            notify("downloadError")
            return
        }
        val transfer = try {
            BlobTransfer(
                filename("https://local.invalid/download", disposition, mime),
                mime ?: "application/octet-stream",
                File.createTempFile("gozar-blob-", ".part", activity.cacheDir))
        } catch (_: Exception) {
            notify("downloadError")
            return
        }
        transfers[token] = transfer
        notify("downloadStarted")
        // fetch(blob:) must execute in the page that created the object URL.
        // Stream moderate chunks to avoid JS string and Android binder limits.
        val tokenJs = JSONObject.quote(token)
        val urlJs = JSONObject.quote(url)
        val script = """
            (async function () {
              const token = $tokenJs;
              try {
                const response = await fetch($urlJs);
                const blob = await response.blob();
                if (blob.size > $maxBlob) throw new Error('File too large');
                GozarFileBridge.begin(token, blob.type || '', blob.size);
                for (let i = 0; i < blob.size; i += 24000) {
                  const part = new Uint8Array(
                    await blob.slice(i, i + 24000).arrayBuffer());
                  let raw = '';
                  for (let j = 0; j < part.length; j++) {
                    raw += String.fromCharCode(part[j]);
                  }
                  GozarFileBridge.chunk(token, btoa(raw));
                }
                GozarFileBridge.finish(token);
              } catch (e) {
                GozarFileBridge.fail(token);
              }
            })();
        """.trimIndent()
        web.evaluateJavascript(script, null)
    }

    inner class BlobPort {
        @JavascriptInterface fun begin(token: String, mime: String, size: Long) {
            val transfer = transfers[token] ?: return
            if (size <= 0 || size > maxBlob) {
                transfers.remove(token)
                transfer.abort()
                notify("downloadError")
                return
            }
            synchronized(transfer) {
                if (transfer.closed) return
                transfer.expectedSize = size
                transfer.started = true
                if (mime.isNotBlank()) transfer.mimeHint = mime
            }
        }

        @JavascriptInterface fun chunk(token: String, encoded: String) {
            val transfer = transfers[token] ?: return
            try {
                val bytes = Base64.decode(encoded, Base64.DEFAULT)
                synchronized(transfer) {
                    if (!transfer.started || transfer.closed ||
                        transfer.written + bytes.size > maxBlob) {
                        throw IllegalStateException("Invalid download chunk")
                    }
                    transfer.output.write(bytes)
                    transfer.written += bytes.size
                }
            } catch (_: Exception) {
                transfers.remove(token)
                transfer.abort()
                notify("downloadError")
            }
        }

        @JavascriptInterface fun finish(token: String) {
            val transfer = transfers.remove(token) ?: return
            synchronized(transfer) {
                if (!transfer.started || transfer.written != transfer.expectedSize) {
                    transfer.abort()
                    notify("downloadError")
                    return
                }
                transfer.close()
            }
            Thread {
                try {
                    transfer.file.inputStream().use { input ->
                        store(input, transfer.filename, transfer.mimeHint, maxBlob)
                    }
                } catch (_: Exception) {
                    notify("downloadError")
                } finally {
                    transfer.file.delete()
                }
            }.start()
        }

        @JavascriptInterface fun fail(token: String) {
            transfers.remove(token)?.let {
                it.abort()
                notify("downloadError")
            }
        }
    }

    fun dispose() {
        transfers.values.forEach { it.abort() }
        transfers.clear()
        // A renderer may already have been destroyed by Android.
        try {
            web.removeJavascriptInterface("GozarFileBridge")
        } catch (_: Exception) { /* Nothing remains to detach. */ }
    }
}
