package ir.channel.telegram_news

import android.app.Activity
import android.content.ContentValues
import android.media.MediaScannerConnection
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.util.Base64
import android.webkit.CookieManager
import android.webkit.JavascriptInterface
import android.webkit.URLUtil
import android.webkit.MimeTypeMap
import android.webkit.WebView
import io.flutter.plugin.common.MethodChannel
import org.json.JSONObject
import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.InputStream
import java.net.HttpURLConnection
import java.net.URL
import java.net.URLConnection
import java.util.UUID
import java.util.concurrent.ConcurrentHashMap

/**
 * A WebView does not download files by itself. Save HTTPS downloads with the
 * site's session cookies, and support blob: links generated by web messengers.
 * Android 10+ MediaStore puts images/videos in the gallery and other files in
 * the public Downloads/Gozar folder, without broad storage permissions.
 */
class GozarSocialDownloads(
    private val activity: Activity,
    private val web: WebView,
    private val index: Int,
    private val events: MethodChannel
) {
    private class BlobTransfer(val filename: String, val mimeHint: String) {
        val bytes = ByteArrayOutputStream()
        var expectedSize = -1L
        var started = false
    }

    private val transfers = ConcurrentHashMap<String, BlobTransfer>()
    private val maxBlob = 30L * 1024 * 1024
    private val maxHttps = 150L * 1024 * 1024

    init {
        // No arbitrary URL or file path can be submitted through this bridge.
        // The only accepted token is a random, short-lived one issued after a
        // user-initiated WebView download for this specific page.
        web.addJavascriptInterface(BlobPort(), "GozarFileBridge")
        web.setDownloadListener { url, userAgent, disposition, mime, _ ->
            val uri = android.net.Uri.parse(url)
            when (uri.scheme?.lowercase()) {
                "https" -> {
                    notify("downloadStarted")
                    val agent = userAgent ?: web.settings.userAgentString
                    Thread {
                        try {
                            val request = URL(url).openConnection() as HttpURLConnection
                            request.connectTimeout = 20000
                            request.readTimeout = 45000
                            request.instanceFollowRedirects = true
                            request.setRequestProperty("User-Agent", agent)
                            CookieManager.getInstance().getCookie(url)?.let {
                                request.setRequestProperty("Cookie", it)
                            }
                            try {
                                if (request.responseCode !in 200..299 ||
                                    request.url.protocol != "https") {
                                    throw IllegalStateException("HTTPS download failed")
                                }
                                val name = filename(url,
                                    request.getHeaderField("Content-Disposition") ?: disposition,
                                    mime)
                                val kind = request.contentType?.substringBefore(';')?.trim()
                                    ?.takeIf { it.isNotBlank() }
                                    ?: mime ?: "application/octet-stream"
                                request.inputStream.use { input ->
                                    store(input, name, kind, maxHttps)
                                }
                            } finally {
                                request.disconnect()
                            }
                        } catch (_: Exception) {
                            notify("downloadError")
                        }
                    }.start()
                }
                "blob" -> downloadBlob(url, disposition, mime)
                else -> notify("downloadError")
            }
        }
    }

    private fun filename(url: String, disposition: String?, mime: String?): String {
        val guessed = URLUtil.guessFileName(url, disposition, mime)
        val sanitized = guessed.substringAfterLast('/').substringAfterLast('\\')
            .replace(Regex("[^\\p{L}\\p{N}._ -]"), "_").take(100)
        return sanitized.ifBlank { "Gozar-download-${System.currentTimeMillis()}" }
    }

    private fun notify(method: String, gallery: Boolean = false) {
        activity.runOnUiThread {
            events.invokeMethod(method, mapOf("index" to index, "gallery" to gallery))
        }
    }

    private fun store(input: InputStream, name: String, mimeHint: String, limit: Long) {
        val mime = if (mimeHint.isBlank() || mimeHint == "application/octet-stream") {
            URLConnection.guessContentTypeFromName(name) ?: "application/octet-stream"
        } else mimeHint
        val gallery = mime.startsWith("image/") || mime.startsWith("video/")
        val extension = MimeTypeMap.getSingleton().getExtensionFromMimeType(mime)
        val displayName = if (gallery && !extension.isNullOrBlank() &&
            !name.lowercase().endsWith(".$extension") &&
            !name.substringAfterLast('.').let { it.length in 2..5 }) {
            "$name.$extension"
        } else name
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            val collection = when {
                mime.startsWith("image/") -> MediaStore.Images.Media.EXTERNAL_CONTENT_URI
                mime.startsWith("video/") -> MediaStore.Video.Media.EXTERNAL_CONTENT_URI
                else -> MediaStore.Downloads.EXTERNAL_CONTENT_URI
            }
            val folder = when {
                mime.startsWith("image/") -> Environment.DIRECTORY_PICTURES
                mime.startsWith("video/") -> Environment.DIRECTORY_MOVIES
                else -> Environment.DIRECTORY_DOWNLOADS
            }
            val values = ContentValues().apply {
                put(MediaStore.MediaColumns.DISPLAY_NAME, displayName)
                put(MediaStore.MediaColumns.MIME_TYPE, mime)
                put(MediaStore.MediaColumns.RELATIVE_PATH, "$folder/Gozar")
                put(MediaStore.MediaColumns.IS_PENDING, 1)
            }
            val uri = activity.contentResolver.insert(collection, values)
                ?: throw IllegalStateException("MediaStore unavailable")
            try {
                activity.contentResolver.openOutputStream(uri)?.use { output ->
                    val buffer = ByteArray(65536)
                    var written = 0L
                    while (true) {
                        val count = input.read(buffer)
                        if (count < 0) break
                        written += count
                        if (written > limit) throw IllegalStateException("File too large")
                        output.write(buffer, 0, count)
                    }
                    if (written == 0L) throw IllegalStateException("Empty download")
                } ?: throw IllegalStateException("Cannot open MediaStore output")
                activity.contentResolver.update(uri, ContentValues().apply {
                    put(MediaStore.MediaColumns.IS_PENDING, 0)
                }, null, null)
                notify("downloadSaved", gallery)
            } catch (error: Exception) {
                activity.contentResolver.delete(uri, null, null)
                throw error
            }
        } else {
            // Gozar's supported A54 is Android 10+, but avoid crashing on older devices.
            val directory = activity.getExternalFilesDir(
                if (gallery) Environment.DIRECTORY_PICTURES else Environment.DIRECTORY_DOWNLOADS
            ) ?: throw IllegalStateException("Storage unavailable")
            directory.mkdirs()
            val output = File(directory, displayName)
            output.outputStream().use { dest -> input.copyTo(dest) }
            if (gallery) MediaScannerConnection.scanFile(
                activity, arrayOf(output.absolutePath), arrayOf(mime), null
            )
            notify("downloadSaved", gallery)
        }
    }

    private fun downloadBlob(url: String, disposition: String?, mime: String?) {
        val token = UUID.randomUUID().toString()
        transfers[token] = BlobTransfer(filename("https://local.invalid/download", disposition, mime),
            mime ?: "application/octet-stream")
        notify("downloadStarted")
        // fetch(blob:) must execute in the page that created the object URL.
        // Stream moderate chunks to avoid JS string and Android binder limits.
        val tokenJs = JSONObject.quote(token)
        val urlJs = JSONObject.quote(url)
        val script = """
            (async function () {
              const token = $tokenJs;
              try {
                const response = await fetch($urlJs);
                const blob = await response.blob();
                if (blob.size > $maxBlob) throw new Error('File too large');
                GozarFileBridge.begin(token, blob.type || '', blob.size);
                const buffer = await blob.arrayBuffer();
                const data = new Uint8Array(buffer);
                for (let i = 0; i < data.length; i += 24000) {
                  const part = data.subarray(i, i + 24000);
                  let raw = '';
                  for (let j = 0; j < part.length; j++) {
                    raw += String.fromCharCode(part[j]);
                  }
                  GozarFileBridge.chunk(token, btoa(raw));
                }
                GozarFileBridge.finish(token);
              } catch (e) {
                GozarFileBridge.fail(token);
              }
            })();
        """.trimIndent()
        web.evaluateJavascript(script, null)
    }

    inner class BlobPort {
        @JavascriptInterface fun begin(token: String, mime: String, size: Long) {
            val transfer = transfers[token] ?: return
            if (size <= 0 || size > maxBlob) {
                transfers.remove(token)
                notify("downloadError")
                return
            }
            transfer.expectedSize = size
            transfer.started = true
            // Blob's actual MIME may be more useful than a generic download hint.
            if (mime.isNotBlank()) {
                transfers[token] = BlobTransfer(transfer.filename, mime).also {
                    it.expectedSize = size
                    it.started = true
                }
            }
        }

        @JavascriptInterface fun chunk(token: String, encoded: String) {
            val transfer = transfers[token] ?: return
            if (!transfer.started) return
            try {
                val bytes = Base64.decode(encoded, Base64.DEFAULT)
                if (transfer.bytes.size().toLong() + bytes.size > maxBlob)
                    throw IllegalStateException("Blob exceeds limit")
                transfer.bytes.write(bytes)
            } catch (_: Exception) {
                transfers.remove(token)
                notify("downloadError")
            }
        }

        @JavascriptInterface fun finish(token: String) {
            val transfer = transfers.remove(token) ?: return
            if (!transfer.started || transfer.bytes.size().toLong() != transfer.expectedSize) {
                notify("downloadError")
                return
            }
            Thread {
                try {
                    ByteArrayInputStream(transfer.bytes.toByteArray()).use { input ->
                        store(input, transfer.filename, transfer.mimeHint, maxBlob)
                    }
                } catch (_: Exception) {
                    notify("downloadError")
                }
            }.start()
        }

        @JavascriptInterface fun fail(token: String) {
            if (transfers.remove(token) != null) notify("downloadError")
        }
    }

    fun dispose() {
        transfers.clear()
        web.removeJavascriptInterface("GozarFileBridge")
    }
}
